version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
      - ./src/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: mikolatero/php5.6-fpm-alpine
    volumes: 
      - ./src/:/var/www/html


  backend:
    container_name: backend-toptal
    build: 
      context: ./toptal-rest-series
      dockerfile: ../Dockerfile.node  
    volumes:
      - ./toptal-rest-series:/usr/src/app
      - /usr/src/app/node_modules

    ports:
      - 3000:3000
    stdin_open: true
